---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: 'myservice '
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  name: 'myservice '
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: 'myservice '
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: 'myservice '
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  name: 'myservice '
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: 'myservice '
      app.kubernetes.io/version: 1.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app.kubernetes.io/name: 'myservice '
        app.kubernetes.io/version: 1.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: albertinadacunha/myservice :1.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: 'myservice '
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
